export { default as AuthorManagement } from "./AuthorManagement";
export { default as BookManagement } from "./BookManagement";
export { default as BookCreate } from "./BookCreate";
export { default as BookEdit } from "./BookEdit";
export { default as BookDetail } from "./BookDetail";
export { default as CategoryManagement } from "./CategoryManagement";
export { default as DashboardHome } from "./DashboardHome";
export { default as OrderManagement } from "./OrderManagement";
export { default as OrderDetail } from "./OrderDetail";
export { default as PublisherManagement } from "./PublisherManagement";
export { default as UserManagement } from "./UserManagement";
export { default as UserDetail } from "./UserDetail";
export { default as UserEdit } from "./UserEdit";
export { default as PublisherCreate } from "./PublisherCreate";
export { default as PublisherEdit } from "./PublisherEdit";

export { default as AuditLogDashboard } from "./AuditLogDashboard";
export { default as ReviewManagement } from "./ReviewManagement";
export { default as LogManagement } from "./LogManagement";
